# Generated by Django 4.2.30 on 2026-07-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likes_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
