# Generated by Django 4.2.30 on 2026-07-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('initiator', 'receiver')},
        ),
    ]
