# Generated by Django 4.2.30 on 2026-07-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('FASH', 'Fashion'), ('TOYS', 'Toys'), ('ELEC', 'Electronics'), ('HOME', 'Home'), ('MISC', 'Miscellaneous')], default='MISC', max_length=4),
        ),
    ]
